### ISSUE TITLE
示例网站登陆不上去

### ISSUE THREAD

**Issue by Shlpeng** [Allenxuxu/mogutouERP#3]
http://demo.mogutou.xyz
这个用户名密码登陆不上去了？

**Comment by Allenxuxu** [comment]
> http://demo.mogutou.xyz
> 这个用户名密码登陆不上去了？

可能又被热心小伙伴改了密码，稍等一会。。我看看

**Comment by Allenxuxu** [comment]
账号： 11223344552

密码： mogutou

没有问题啊，没被改

**Comment by Shlpeng** [comment]
说账号不存在

**Comment by Shlpeng** [comment]
要不换个账号或者增加个账号？

**Comment by Shlpeng** [comment]
(/Users/shlpeng/go/src/github.com/Allenxuxu/mogutouERP/models/core.go:30) 
[2019-12-10 07:22:31]  Error 1067: Invalid default value for 'state' 
panic: Error 1146: Table 'mgt.custormer_orders' doesn't exist

**Comment by Allenxuxu** [comment]
> 说账号不存在

搞错了

11223344552 
mogutou

**Comment by Allenxuxu** [comment]
> (/Users/shlpeng/go/src/github.com/Allenxuxu/mogutouERP/models/core.go:30)
> [2019-12-10 07:22:31] Error 1067: Invalid default value for 'state'
> panic: Error 1146: Table 'mgt.custormer_orders' doesn't exist

这个是表不存在？？
操作步骤，错误发生场景，详细点。

**Comment by Shlpeng** [comment]
直接启动就报错。就是我代码检索下来，修改了数据库链接信息，执行make run的时候报错了，但是这个表之前的其他表已经自动创建了

**Comment by Shlpeng** [comment]
commodities、roles、users三个创建好的表名

**Comment by Shlpeng** [comment]
(/Users/shlpeng/go/src/github.com/Allenxuxu/mogutouERP/models/core.go:30) 
[2019-12-12 00:20:14]  Error 1067: Invalid default value for 'state' 
panic: Error 1146: Table 'mgt.custormer_orders' doesn't exist

**Comment by Shlpeng** [comment]
`gorm:"default:''"` 报错

**Comment by Shlpeng** [comment]
去掉就好了

**Comment by itstmyi** [comment]
刚才提示：账号不存在。

**Comment by Allenxuxu** [comment]
> 刚才提示：账号不存在。

账号： 11223344552

密码： mogutou

这个应该可以的，我刚试过

**Comment by itstmyi** [comment]
现在可以了。不知道过段时间是不是又会出现一次

**Comment by Allenxuxu** [comment]
> 现在可以了。不知道过段时间是不是又会出现一次

有的小伙伴会去尝试改密码😄，是个体验账号，大家都别改就好了，或者改完记得改回来。

**Comment by itstmyi** [comment]
看起来还比较简单，可以往扩展功能和接口收费方向发展下，基础功能免费，云服务我觉得可能性比较小，安全比较难控制。

**Comment by Allenxuxu** [comment]
> 看起来还比较简单，可以往扩展功能和接口收费方向发展下，基础功能免费，云服务我觉得可能性比较小，安全比较难控制。

是的，目前也没有推广，增加新功能，大学时写的了。
